### ISSUE TITLE
Feature flags docs

### ISSUE THREAD

**Issue by molpopgen** [tskit-dev/tskit-rust#256]
We have the docs building for all the public API.
This means that it is not immediately obvious that some
API bits are due to feature flags.

We should have a section in the doc of each item:

```markdown
# Feature flags

This thing requires the cargo feature "foo"
```

**Comment by MomoLangenstein** [comment]
Since docs are built using nightly on `docs.rs`, you could make use of the following:

https://doc.rust-lang.org/beta/unstable-book/language-features/doc-cfg.html

https://docs.rs/about/builds

i.e. enable a feature on docs builds, that enabled the unstable `doc_cfg` feature, which allows you to add `#[doc(cfg(...))]` to any public item which is `cfg`-ed.

See https://docs.rs/syn/latest/syn/ for an example of what that looks like

**Comment by molpopgen** [comment]
Thanks!  I'd just read this in "Rust for Rustaceans", which is what got me thinking about it.

**Comment by molpopgen** [comment]
It does seem like there's some "trust" involved that this will work.  I'm unable to get the `docs.rs` commands from their README to work locally to confirm that the changes actually do anything.
